"""add workspace and workspace_members tables

Revision ID: 82bd834f65fb
Revises: bb9ec3d53bd6
Create Date: 2026-05-11 00:52:18.988911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bd834f65fb'
down_revision: Union[str, Sequence[str], None] = 'bb9ec3d53bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_index(op.f('ix_workspaces_workspace_id'), 'workspaces', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_member_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('workspace_member_id')
    )
    op.create_index(op.f('ix_workspace_members_workspace_member_id'), 'workspace_members', ['workspace_member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_members_workspace_member_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_workspace_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
